### ISSUE TITLE
Mysterious reviewer 2 question

### ISSUE THREAD

**Issue by tintori** [dredge-bio/dredge#59]
Reviewer 2 had this question that I don't really understand. It's clear that there is no urgent ask here, but I will have to address it (at least enough to say "Great idea, we hope to include this in the future", or "Never in a million years because that's not the point of the project" or whatever) in the letter that I write to the editor when we resubmit.

Do you know what the comment means?

> 4. Is it possible to upgrade DrEdGE to a web server in the future (Not required right away)? Users can make interactive visualization by only uploading gene expression data. No python, no R. Anyone can do it.

**Comment by ptgolden** [comment]
They are asking if we could have DrEdGE become something to which they can upload their RNAseq data. Then it would run the statistical tests, configure everything itself, and have a ready-to-use DrEdGE visualization there.

That's definitely something we talked about before, but only as (far) future work
